import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;

import repositories.IRepository;
import repositories.impl.EmployeeBuilder;
import repositories.impl.EmployeeRepository;
import domain.Employee;

public class Main {
		
		public static void main(String[] args) {
			String url ="jdbc:hsqldb:hsql://localhost/workdb";
		
			
			Employee jnowak = new Employee();
			jnowak.setBonus(200);
			jnowak.setSalary(2000);
			
			try 
			{
				EmployeeBuilder ebuilder = new EmployeeBuilder();
				Connection connection = DriverManager.getConnection(url);
				/*
				  String createTable =
				 
						"CREATE TABLE employees("
						+ "id int GENERATED BY DEFAULT AS IDENTITY,"
						+ "workplace VARCHAR(20),"
						+ "salary VARCHAR(20)"
						+ ")";
				Statement stmt = connection.createStatement();
				stmt.executeUpdate(createTable);
				*/
				IRepository<Employee> employees = new EmployeeRepository(connection, ebuilder);
				employees.save(jnowak);
				List<Employee> EmployeesFromDb = employees.getAll();
				
				for(Employee EmployeeFromDb : EmployeesFromDb)
					System.out.println(EmployeeFromDb.getId()+" "+EmployeeFromDb.getBonus()+" "+EmployeeFromDb.getSalary());
				Employee employee = employees.get(1);
				employee.setSalary(2000);
				employees.update(employee);
				employees.delete(EmployeesFromDb.get(0));
				for(Employee EmployeeFromDb : employees.getAll())
					System.out.println(EmployeeFromDb.getId()+" "+EmployeeFromDb.getBonus()+" "+EmployeeFromDb.getSalary());
				
				
			} catch (Exception e) {
				e.printStackTrace();
			}
			System.out.println("koniec");
		}

	}

